# Generated by Django 4.1.2 on 2022-11-07 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mb_del_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mb_regdate',
        ),
    ]
