# Generated by Django 4.1.2 on 2022-11-07 01:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_mb_del_date_remove_user_mb_regdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mb_del_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mb_regdate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
