# Generated by Django 4.1.2 on 2022-11-14 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_userseller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='point',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.DeleteModel(
            name='UserSeller',
        ),
    ]
