# Generated by Django 4.1.2 on 2022-11-14 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profit',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='profitdone',
            name='amount',
        ),
        migrations.AddField(
            model_name='profit',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profit',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profitdone',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profit',
            name='profit_done',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profit.profitdone'),
        ),
        migrations.AlterField(
            model_name='profit',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='profitdone',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
