# Generated by Django 4.1.2 on 2022-11-14 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profit', '0002_remove_profit_amount_remove_profitdone_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit',
            name='payment_fee',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
