# Generated by Django 4.1.2 on 2022-11-14 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_orderitem_shipping_fee'),
        ('profit', '0003_alter_profit_payment_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profit',
            old_name='paid_amount',
            new_name='charge_amount',
        ),
        migrations.RenameField(
            model_name='profit',
            old_name='shipping_fee',
            new_name='profit_amount',
        ),
        migrations.RenameField(
            model_name='profitdone',
            old_name='paid_amount',
            new_name='profit_done_amount',
        ),
        migrations.RenameField(
            model_name='profitdone',
            old_name='shipping_fee',
            new_name='total_payment_fee',
        ),
        migrations.RemoveField(
            model_name='profit',
            name='is_done',
        ),
        migrations.RemoveField(
            model_name='profitdone',
            name='payment_fee',
        ),
        migrations.AddField(
            model_name='profit',
            name='order_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.orderitem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profitdone',
            name='total_profit_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profitdone',
            name='total_shipping_fee',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profit',
            name='payment_fee',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
