# Generated by Django 4.1.2 on 2022-10-28 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productqna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_column='product_name', max_length=255),
        ),
    ]
