# Generated by Django 4.1.2 on 2022-11-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_qna_qna_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='answered_at',
            field=models.DateTimeField(null=True),
        ),
    ]
