# Generated by Django 4.1.2 on 2022-11-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_orderitem_shipping_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_status',
            new_name='order_item_status',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='accepted_at',
            new_name='responded_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_responded',
            field=models.BooleanField(default=False, verbose_name='셀러가 주문에 응답했는지'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='is_refund_requested',
            field=models.BooleanField(default=False, verbose_name='셀러에게 환불요청 했는지'),
        ),
    ]
